hyperskill_project:
  id: 264
  ide_files: https://cogniterra.org/media/attachments/lesson/26667/additional_files.json
  is_template_based: false
  use_ide: true
  environment: unittest
update_date: "Wed, 05 Feb 2025 18:39:01 UTC"
stages:
  - id: 1335
    step: 20546
    is_completed: true
  - id: 1336
    step: 20547
    is_completed: true
  - id: 1337
    step: 20548
    is_completed: true
  - id: 1338
    step: 20549
    is_completed: true
topics:
  0:
    - title: Operating systems
      theory_id: 9704
    - title: Command line overview
      theory_id: 8977
    - title: Parameters and options
      theory_id: 9746
    - title: Working with file modes and permissions
      theory_id: 13961
    - title: Working with SQLite
      theory_id: 17163
    - title: Introduction to Python
      theory_id: 47352
    - title: Multi-line programs
      theory_id: 47555
    - title: Taking user's input
      theory_id: 47680
    - title: Program with numbers
      theory_id: 47734
    - title: Importing modules
      theory_id: 6019
    - title: Creating modules
      theory_id: 6057
    - title: Multiple modules. Package
      theory_id: 6384
    - title: Installing packages with pip
      theory_id: 6230
    - title: PyCharm basics
      theory_id: 6193
    - title: Files
      theory_id: 13025
    - title: What are databases
      theory_id: 8497
    - title: "SQL: structured query language"
      theory_id: 7054
    - title: Running Python applications in PyCharm
      theory_id: 19153
    - title: Basic data types
      theory_id: 7123
    - title: Literals
      theory_id: 7400
    - title: Arithmetic expressions
      theory_id: 7409
    - title: Basic CREATE statement
      theory_id: 9084
    - title: Basic SELECT statement
      theory_id: 7392
    - title: SELECT FROM statement
      theory_id: 8611
    - title: Logic and comparison expressions
      theory_id: 8619
    - title: Basic INSERT statement
      theory_id: 9059
    - title: Introduction to SQLite
      theory_id: 12165
    - title: File types
      theory_id: 13017
    - title: Program execution
      theory_id: 6047
    - title: Errors
      theory_id: 6052
    - title: Exceptions
      theory_id: 6042
    - title: Built-in exceptions
      theory_id: 11680
    - title: Exception handling
      theory_id: 6270
    - title: File modes and permissions
      theory_id: 13953
    - title: Files in Python
      theory_id: 8691
    - title: "Real-time interpreter: Shell"
      theory_id: 8133
    - title: Basic data types
      theory_id: 47516
    - title: Variables
      theory_id: 47536
    - title: "Integer arithmetic: basic operations"
      theory_id: 47564
    - title: Invoking functions
      theory_id: 5891
    - title: Declaring functions
      theory_id: 5900
    - title: Global vs local. Scopes
      theory_id: 6322
    - title: Quotes and multi-line strings
      theory_id: 5814
    - title: String formatting
      theory_id: 6037
  1:
    - title: If statement
      theory_id: 5953
    - title: Else statement
      theory_id: 5932
    - title: For loop
      theory_id: 6065
    - title: What is object-oriented programming
      theory_id: 3614
    - title: Elif statement
      theory_id: 5926
    - title: Class
      theory_id: 6661
    - title: Class instances
      theory_id: 6669
    - title: Relational Data Model
      theory_id: 13785
    - title: Introduction to logging
      theory_id: 5538
    - title: JSON
      theory_id: 6854
    - title: XML
      theory_id: 6901
    - title: Data and object mapping
      theory_id: 8262
    - title: Object-Relational Mapping (ORM)
      theory_id: 8312
    - title: Intro to SQL Alchemy
      theory_id: 12935
    - title: Reading files
      theory_id: 8139
    - title: Intro to MySQL
      theory_id: 16662
    - title: SQL Alchemy mappings
      theory_id: 13033
    - title: SQL Alchemy querying and filtering
      theory_id: 15111
    - title: Writing files
      theory_id: 8334
    - title: Context manager
      theory_id: 8702
    - title: CSV
      theory_id: 13164
    - title: Working with CSV
      theory_id: 11724
    - title: Boolean type and operations. True and false
      theory_id: 6025
    - title: Comparisons
      theory_id: 5920
    - title: List
      theory_id: 5979
    - title: Indexes
      theory_id: 6189
    - title: Tuple
      theory_id: 7462
    - title: "Working with strings: basic methods"
      theory_id: 6842
    - title: Escape sequences
      theory_id: 7130
    - title: Splitting strings and joining lists
      theory_id: 6972
    - title: Functional decomposition
      theory_id: 9571
    - title: List comprehension
      theory_id: 6315
    - title: Dictionary
      theory_id: 6481
    - title: Nested lists
      theory_id: 6938
    - title: Alter table
      theory_id: 9579
    - title: PRIMARY KEY constraint
      theory_id: 9781
  2:
    - title: Basic DELETE statement
      theory_id: 9075
    - title: Basic UPDATE statement
      theory_id: 9067
    - title: Updating selected rows
      theory_id: 9603
    - title: SQL Alchemy updating and deleting data
      theory_id: 15776
  3:
    - title: Methods
      theory_id: 6931
    - title: Methods and attributes
      theory_id: 6981
    - title: Magic methods
      theory_id: 7139
